version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    networks:
      - binaries-app
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - pg-database
    ports:
      - '5000:5000'
    environment:
      - BACKEND_URL:${BACKEND_URL}
      - PORT:${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BINARIES_EMAIL=${BINARIES_EMAIL}
      - BINARIES_PASSWORD=${BINARIES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=pg-database
    networks:
      - binaries-app
    volumes:
      - ./backend:/app/backend
  pg-database:
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - binaries-app
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  binaries-app:
    driver: bridge

    
