version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    networks:
      - binaries-app
    ports:
      - '5174:5174'
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - pg-database
    ports:
      - '5000:5000'
    environment:
      - BACKEND_URL:http://localhost:5000
      - PORT:5000
      - JWT_SECRET_KEY=vfgbdh%^2DSw@
      - BINARIES_EMAIL=mohsinrock4u2@hotmail.com
      - BINARIES_PASSWORD=Mohsin1?
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_DB=binaries
      - PG_HOST=pg-database
    networks:
      - binaries-app
  pg-database:
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - binaries-app
    restart: always
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_DB=binaries
      - PG_HOST=PG_HOST
networks:
  binaries-app:
    driver: bridge

    
